spring.application.name=digital-backend-application

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/${db}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.hikari.maximum-pool-size=10

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}