spring.application.name=digital-backend-application

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/${db}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.web.error.include-stacktrace=always

# JWT Configuration
jwt.secret.string=${JWT_SECRET}
jwt.expiration.time=${JWT_EXPIRATION_TIME}
jwt.refresh.expiration.time=${JWT_REFRESH_EXPIRATION_TIME}