spring.application.name=digital-backend-application

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB:digitalbank}
spring.datasource.username=${POSTGRES_USER:dbadmin}
spring.datasource.password=${POSTGRES_PASSWORD:dbpass123}
spring.datasource.hikari.maximum-pool-size=10