package com.groupa.digitalbackendapplication.domain.enums;

public enum ActionType {
    USER_REGISTRATION,
    USER_LOGIN,
    ACCOUNT_CREATED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_UNSUSPENDED,
    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,
    TIER_UPGRADED,
    TRANSACTION_INITIATED,
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    TRANSACTION_REVERSED,
    USER_PROFILE_FETCHED,
    PENDING_KYC_FETCHED,
    TRANSACTION_FETCHED,
    BANK_OVERVIEW,
    ADMIN_REGISTRATION,
    PASSWORD_CHANGED,
    ANOTHER_ACCESS_TOKEN,
    DEBIT_TRANSACTION_SUCCESS,
    SELF_CREDIT_TRANSACTION_SUCCESS,
    TRANSACTION_REQUERIED,
    USER_LOGOUT
}
